name: PR Preview

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.BOT }}
          message: |
            ## Deploying with :page_facing_up: GitHub Pages

            | **Commit:** | ${{ github.event.pull_request.head.sha }} |
            | :-- | :-- |
            | **Status:** | 🔨 Building |
            | **Deploy Log:** | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |

      - uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - if: ${{ github.event.action == 'opened'}}
        run: gh repo create win11bot/${{ github.event.pull_request.number }} --public
        env:
          GITHUB_TOKEN: ${{ secrets.BOT }}

      - name: Install NPM packages
        run: npm ci

      - name: Get translations
        run: npm run crowdin download
        env:
          api_token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Build
        run: npm run ghbuild
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.BOT }}
          publish_dir: ./build
          external_repository: win11bot/${{ github.event.pull_request.number }}

      - name: Sleep
        run: sleep 1m
        shell: bash

      - name: Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.BOT }}
          message: |
            ## Deployed with :page_facing_up: GitHub Pages

            | **Commit:** | ${{ github.event.pull_request.head.sha }} |
            | :-- | :-- |
            | **Status:** | ✅ Success |
            | **Preview:** | https://pr-preview.win11react.com/${{ github.event.pull_request.number }} |
            | **Deploy Log:** | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |

      - if: ${{ failure() }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.BOT }}
          message: |
            ## Deploying with :page_facing_up: GitHub Pages

            | **Commit:** | ${{ github.event.pull_request.head.sha }} |
            | :-- | :-- |
            | **Status:** | ❌ Failure |
            | **Deploy Log:** | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
